<a href="https://colab.research.google.com/github/XavierReyes1/Tarea1.2/blob/main/Ejercicio%231.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd

df = pd.read_csv('./ventas.csv')
#Ver cantidad de filas del dataframe
df.shape
df.head()

    Producto  Cantidad  Precio_Unitario
0     Webcam        15               74
1    Monitor        19              866
2  Impresora        12              848
3     Webcam         3              530
4    Teclado         5              353

In [6]:
Cantida_categoria = df.groupby('Producto')['Cantidad'].sum()
Cantida_categoria

Producto
Auriculares     53
Impresora       65
Laptop          49
Monitor        113
Mouse           55
Silla Gamer     77
Teclado         73
Webcam          56
Name: Cantidad, dtype: int64

In [16]:
Mayor_ventas = Cantida_categoria.sort_values(ascending=False).head(1)
Mayor_ventas

Producto
Monitor    113
Name: Cantidad, dtype: int64

In [18]:
precio_promedio = df.groupby('Producto')['Precio_Unitario'].mean()
precio_promedio

Producto
Auriculares    437.500000
Impresora      490.000000
Laptop         771.333333
Monitor        669.500000
Mouse          354.000000
Silla Gamer    480.500000
Teclado        530.285714
Webcam         340.000000
Name: Precio_Unitario, dtype: float64